# Generated by Django 2.2.22 on 2021-05-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20210521_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
