# Generated by Django 2.2.22 on 2021-05-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20210521_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={'permissions': (('setar nfe', 'Usuario pode alterar parametro NFe'),)},
        ),
    ]
