# Generated by Django 2.2.22 on 2021-05-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_auto_20210522_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar parametro NFe'),)},
        ),
    ]
