# Generated by Django 2.2.22 on 2021-05-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210519_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
