# Generated by Django 2.2.22 on 2021-05-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20210521_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='nfe_emitida',
            field=models.BooleanField(default=False),
        ),
    ]
