# Generated by Django 2.2.22 on 2021-05-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20210521_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
