# Generated by Django 2.2.22 on 2021-05-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_delete_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deletar clientes'),)},
        ),
    ]
